In [1]:
import numpy as np
import pandas as pd
from numpy import random
from scipy.spatial import distance

%load_ext line_profiler

In [1]:
__VERSION__


NameError: name '__VERSION__' is not defined

In [14]:

def closest_node(node, nodes):
    closest_index = distance.cdist([node], nodes).argmin()
    return nodes[closest_index]

a = random.randint(1000, size=(5000000, 4))

some_pt = (1, 2, 3, 4)

# %lprun -f closest_node closest_node(some_pt, a)
distance.cdist(a, [some_pt])[0]

array([995.11707854])

In [ ]:
import numpy as np
import tensorflow as tf

# Create some example data
X_train = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10]], dtype=np.float32)
y_train = np.array([[2], [4], [6], [8], [10]], dtype=np.float32)


In [4]:
X_train


array([[ 1.,  2.],
       [ 3.,  4.],
       [ 5.,  6.],
       [ 7.,  8.],
       [ 9., 10.]], dtype=float32)

In [ ]:

# Define model parameters
learning_rate = 0.01
training_epochs = 1000

# Define the linear regression model
model = tf.keras.models.Sequential([
  tf.keras.layers.Dense(1, input_shape=(2,), activation='linear')])
# Define the optimizer and compile the model
optimizer = tf.keras.optimizers.SGD(learning_rate)
model.compile(optimizer=optimizer, loss='mse')

#Train the model
model.fit(X_train, y_train, epochs=training_epochs)

#Print the learned parameters
weights, bias = model.layers[0].get_weights()
print("Optimized weights:", weights)
print("Optimized bias:", bias)

In [ ]:
)
y_train = np.array([[2], [4], [6], [8], [10]], dtype=np.float32)

# Define model parameters
learning_rate = 0.01
training_epochs = 1000

# Define the linear regression model
model = tf.keras.models.Sequential([
  tf.keras.layers.Dense(1, input_shape=(2,), activation='linear')])
# Define the optimizer and compile the model
optimizer = tf.keras.optimizers.SGD(learning_rate)
model.compile(optimizer=optimizer, loss='mse')

#Train the model
model.fit(X_train, y_train, epochs=training_epochs)

#Print the learned parameters
weights, bias = model.layers[0].get_weights()
print("Optimized weights:", weights)
print("Optimized bias:", bias)

In [2]:
df = pd.read_csv("output/training_data.csv")

NameError: name 'pd' is not defined

In [2]:
import torch
from torch.nn.functional import normalize

Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.
Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.


In [3]:
t = torch.tensor([[1.,2.,3.],[4.,5.,6.]])
print("Tensor:", t)

Tensor: tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [4]:
t1 = normalize(t, p=1.0, dim = 1)
t2 = normalize(t, p=2.0, dim = 0)

In [5]:
print("Normalized tensor:", t1)
print("Normalized tensor:", t2)

Normalized tensor: tensor([[0.1667, 0.3333, 0.5000],
        [0.2667, 0.3333, 0.4000]])
Normalized tensor: tensor([[0.2425, 0.3714, 0.4472],
        [0.9701, 0.9285, 0.8944]])


In [6]:
normalize(t, p=1.0, dim = 0)

tensor([[0.2000, 0.2857, 0.3333],
        [0.8000, 0.7143, 0.6667]])

In [7]:
normalize(t, p=1.0)

tensor([[0.1667, 0.3333, 0.5000],
        [0.2667, 0.3333, 0.4000]])